### ISSUE TITLE
"TypeError: __WEBPACK_IMPORTED_MODULE_2_firebase__.firestore is not a function"

### ISSUE THREAD

**Issue by eeerrrttty** [vuejs/vue#8894]
Probable a incompatibility with firebase SDK 5.5.2

After updating my firebase to 5.5.2 from 5.4.2 i got this error ->

TypeError: __WEBPACK_IMPORTED_MODULE_2_firebase__.firestore is not a function

My app was working pretty well before, returning to version 5.4.2 stops the bug.
