### ISSUE TITLE
2.5.14 introduces TypeError bind is not a function

### ISSUE THREAD

**Issue by rjoo** [vuejs/vue#8017]
### Version
2.5.14

### Reproduction link
[https://jsfiddle.net/bad4a8mb/1/](https://jsfiddle.net/bad4a8mb/1/)

### Steps to reproduce
Provide a non function to the `bind` utility method.

### What is expected?
In <= 2.5.13, it rendered but failed silently: https://jsfiddle.net/ujxu9mvd/. Not sure if we'd want to keep that expectation, but existing projects will fail to render completely. A dev-mode warning at the very least will be helpful in identifying the issue.

### What is actually happening?
Uncaught TypeError

---
The refactoring of the `bind` method to use the native bind, exposes a coding error when upgrading from 2.5.13. We have a fairly large codebase and one of the developers mistakenly added an object as a component method (eg. a global Vue events instance). It made its way into production and worked fine until upgrading to 2.5.14. It took a while to find it as there was no clear indication as to where the error was happening.

Some other devs experienced this as well:
https://github.com/vuejs/vue/pull/7491
https://github.com/vuejs/vue/commit/324672a4621a3123cac90b18d4b1818bb33dddc6

**Comment by posva** [comment]
A warning in dev mode would be fine

**Comment by thedamon** [comment]
This was a weird one to track down! We had a js file being used as a mixin, but one of the exports was an array.
