### ISSUE TITLE
Uncaught TypeError: Object.entries is not a function on OSX

### ISSUE THREAD

**Issue by maarteNNNN** [vuejs/vue#8956]
### Version
2.5.17

### Reproduction link
[https://beautysalonfiore.be](https://beautysalonfiore.be)

### Steps to reproduce
I'm having this problem on OSX. On Windows, Android and Linux I don't encounter this problem. I have tried to rebuild it. Google it, found alot of non Vue related issues. It doesn't work on an iPad aswell. However on an iPhone it does. What's most likely this problem?

This project is build with vue-cli 3.0.5.

### What is expected?
That the bundle to work on OSX

### What is actually happening?
I gives a TypeError: Object.entries is not a function on OSX

---
It used to work fine. Until one build started to show errors on just Apple related products except the iPhone. I haven't found any issue related to this. I'm willing to share source code if necessary.

**Comment by posva** [comment]
The repro is necessary...

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by yyx990803** [comment]
This is also a Vue CLI issue, likely related to Babel polyfill behavior. Please post the issue with proper **minimal reproduction** (no entire projects please) to the vue-cli repo instead.

**Comment by Justineo** [comment]
@maarteNNNN Please do not share the whole repo. You can create a repo on GitHub and provide the minimal code that reproduces the current issue.

**Comment by maarteNNNN** [comment]
It was pretty difficult to reproduce because I don't own a Mac. However through @yyx990803 reply I was able to scope out the problem, it's within the package `vue2-google-maps`. [Link to Stack Overflow](https://stackoverflow.com/questions/52475423/vue-3-cli-how-to-add-babel-polyfill-for-object-entries). This resolved the issue for OSX! Thanks!
