### ISSUE TITLE
v1.0.28 working but v2.0.1 not working

### ISSUE THREAD

**Issue by Nisthar** [vuejs/vue#3881]
I was working with v1.0.28 and it was working without any errors. I recently switched to v2.0.1 and its giving me multiple warnings and errors.

I get warnings for declaring initial values of select components in the app's data option. I ignored it as its warning. But i am getting an error `TypeError: binding.value.some is not a function` and the app is not working. it works if i switch back to v1.0.28 

How can i fix this?

**Comment by aphofstede** [comment]
Did you follow the [Migration Guide](http://vuejs.org/guide/migration.html)?

**Comment by Nisthar** [comment]
@aphofstede Ok, I didn't checked it. Let me try it.
