### ISSUE TITLE
Vuejs type inference does not work with TS 3.4.x

### ISSUE THREAD

**Issue by p-kuen** [vuejs/vue#9873]
### Version
2.6.10

### Reproduction link
[https://github.com/Patcher56/ts3.4.x-vuejs-issue](https://github.com/Patcher56/ts3.4.x-vuejs-issue)

### Steps to reproduce
1. create a new vue typescript project (without class syntax) `vue create test-ts`
2. open `src/components/HelloWorld.vue`
3. add a data variable and try to access it in a computed property

### What is expected?
No errors (as the data is defined)

### What is actually happening?
Typescript error 2339 telling me
```Property 'test' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{ msg: string; }>>'.```

![image](https://user-images.githubusercontent.com/2443710/56112638-f5ae1500-5f5b-11e9-82c5-bc2cd4f52831.png)

---
I think this has something to do with the changed type inference in Typescript 3.4.x.

**Important**: Change vetur settings to use workspace dependencies to show errors directly in vscode, else you will only get the error when using `yarn serve`.

**Comment by LinusBorg** [comment]
Seems to belong into the vetur repository then, right?

**Comment by Patcher56** [comment]
No, because the errors also appear in the terminal when using `yarn serve`.
Vetur is just responsible for showing me the errors directly in vscode.

**Comment by HerringtonDarkholme** [comment]
Looks like TS3.4 has multiple inference issue... 

The minimal repro:

```ts
Vue.component('test', {
  data() {
    return {
      test: 123
    }
  },
  computed: {
    ttt() {
      return this.test + 1
    }
  },
})
```

Also spotted another failure:

The catch-all type signature of component
```ts
  component(id: string, definition?: ComponentOptions<V>): ExtendedVue<V, {}, {}, {}, {}>;
```
is causing union type to fail checking. 

I need more time for investigation...

**Comment by DaKoala** [comment]
I wonder if properties in `data` are supposed to become properties of the instance when using TypeScript?

**Comment by LinusBorg** [comment]
Of course...

**Comment by mrozekma** [comment]
I filed the same bug against Typescript (Microsoft/TypeScript#30854)

**Comment by HerringtonDarkholme** [comment]
Minimal repro:

```ts
type TypedDef<Data, Computed> =
  ComponentOptions<Data, Computed> &
  ThisType<Data & Computed>

type DataDef<Data> = () => Data

export interface ComponentOptions<Data, Computed> {
  data?: DataDef<Data>
  computed?: Accessors<Computed>
}
export type Accessors<T> = {
  [K in keyof T]: () => T[K]
}

declare function component<Data, Computed>(def: TypedDef<Data, Computed>): void;

component({
  data() {
    return {
      foo: 23
    }
  },
  computed: {
    bar() {
      // return this.foo + 1 // comment out the return solves the problem
    }
  }
})

```

The problem seems to be cyclic inference issue. I think it should goes to TypeScript's repo.

**Comment by pikax** [comment]
One workaround is assigning a return type to computed

```typescript
type TypedDef<Data, Computed> =
  ComponentOptions<Data, Computed> &
  ThisType<Data & Computed>

type DataDef<Data> = () => Data

export interface ComponentOptions<Data, Computed> {
  data?: DataDef<Data>
  computed?: Accessors<Computed>
}
export type Accessors<T> = {
  [K in keyof T]: () => T[K]
}

declare function component<Data, Computed>(def: TypedDef<Data, Computed>): void;

component({
  data() {
    return {
      foo: 23
    }
  },
  computed: {
    bar(): number { // adding the return type, seems to solve the error
      return this.foo + 1
    }
  }
})
```

**Comment by mrozekma** [comment]
> One workaround is assigning a return type to computed

Good call. Just discovered that workaround is documented [here](https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types).

**Comment by HerringtonDarkholme** [comment]
The best way to avoid the issue now is to annotate return type of computed method... We cannot make much progress since it is an upstream issue in TS.

**Comment by kjleitz** [comment]
> The best way to avoid the issue now is to annotate return type of computed method... We cannot make much progress since it is an upstream issue in TS.

Unfortunately it also happens if you have a validator on a prop:

```ts
export default Vue.extend({
  props: {
    foobar: {
      required: true,
      type: String,
      validator(foobar: string): boolean { return ['foo', 'bar'].includes(foobar); },
    },
  },

  data(): { initialFoobar: string } {
    return {
      initialFoobar: this.foobar, //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    };
  },

  computed: {
    foobang(): string {
      return `${this.foobar}!`; //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    },
  },
});
```

Breaks our entire build, easily 100+ errors after stepping up from TS v3.3.3333 to v3.4.4. Too bad, too, because this version of TS introduced some handy features for _exactly_ what I'm working on right now... 😩

**Comment by kjleitz** [comment]
Also happens if you have a `Function`-type prop:

```ts
export default Vue.extend({
  props: {
    foobar: {
      required: true,
      type: String,
    },

    // With this, errors. Without this, no errors.
    someFunc: {
      required: true,
      type: Function,
    },
  },

  data(): { initialFoobar: string } {
    return {
      initialFoobar: this.foobar, //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    };
  },

  computed: {
    foobang(): string {
      return `${this.foobar}!`; //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    },
  },
});
```

**Comment by kjleitz** [comment]
(Note: the two examples I gave are **not fixed** by the workaround mentioned)

**Comment by pikax** [comment]
@kjleitz not sure what is the issue on my vscode
![image](https://user-images.githubusercontent.com/4620458/56560361-1f8abb80-659c-11e9-845d-aaf38e78fd49.png)

I would recommend annotation the function with PropType
```ts
export default Vue.extend({
  props: {
    foobar: {
      required: true,
      type: String,
    },

    someFunc: {
      required: true,
      type: Function as PropType<()=>any>, // try annotate with a type
    },
  },

  data(): { initialFoobar: string } {
    return {
      initialFoobar: this.foobar, //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    };
  },

  computed: {
    foobang(): string {
      return `${this.foobar}!`; //=> Property 'foobar' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<{}>>'
    },
  },
});
```

**Comment by HerringtonDarkholme** [comment]
Please refer to the comment here:
https://github.com/Microsoft/TypeScript/issues/30854#issuecomment-485893681

**Comment by SilverLeaves** [comment]
```ts
//`/types/myVue.d.ts`
import Vue from "vue";
declare module "vue/types/vue" {
  interface Vue {
    $myConfig: string;
  }
}
```

![图片](https://user-images.githubusercontent.com/31165554/56888820-8b42bc00-6aa7-11e9-93ff-ee0a464e55b4.png)

**Comment by jackkoppa** [comment]
We also had a component start throwing a lot of errors after upgrading from TS `3.3.3333` to `3.4.5`

Thanks to [this comment](https://github.com/Microsoft/TypeScript/issues/30854#issuecomment-485893681), went back and checked that component and, sure enough, one of the computed properties did not have a return type annotated. With that annotation added, the build compiled without issue. 

Per the TS comment, perhaps [the docs](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/typescript.md#annotating-return-types) would be best updated as 
"you **will** need to annotate the return type on methods like `render` and those in `computed`"

**Comment by DanielRosenwasser** [comment]
Yeah, unfortunately it sounds like this was just the same limitation we've always known. My best advice is to make an ESLint rule that catches this, since it is hard to report circularities for us during inference.

**Comment by ProTip** [comment]
To add to @kjleitz unresolved issues, a prop type of `Vue` also breaks it.

**Comment by zurp** [comment]
For anyone getting this error via vetur, but not in console: using `required` seems to stop it from screaming.

![](https://i.imgur.com/3GzYB1k.png)

**Comment by tiagoad** [comment]
I found a very similar issue, with the exact same error, if I used a render() method that used some "props" and wasn't annotated as returning VNode.

Weirdly, instead of getting errors about the render method, or about "props", I got errors about some "data" I used in the mounted() and beforeDestroy() methods.

**Comment by Patcher56** [comment]
Best workaround is to use the new [Vue Composition API](https://vue-composition-api-rfc.netlify.com/). It is a lot cleaner for typescript and works also with typescript versions > 3.3.4000.

**Comment by AlanKnightly** [comment]
I just Wonder Any Workaround that can Work? 
I met this and spent hours for no solution......Seems this has been a problem for over 2 years???

**Comment by AlanKnightly** [comment]
> Best workaround is to use the new [Vue Composition API](https://vue-composition-api-rfc.netlify.com/). It is a lot cleaner for typescript and works also with typescript versions > 3.3.4000.

when using composition api, I NEED TO access my custom props in setup function, and I always get type error saying "Property 'pagination' does not exist on type xxx", so this is never a workaround, i think.

**Comment by manigandham** [comment]
@AlanKnightly this has been working for me:

```ts
import { createComponent } from '@vue/composition-api';

export default createComponent({
    props: {
        rows: Array,
        page: Number,
        filterKey: String
    },
    setup(props, context) {

        const currentPage = props.page;

        return {
            currentPage
        };
    }
});

```

**Comment by posva** [comment]
Closing as this cannot be fixed and is documented: https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types
