### ISSUE TITLE
Calling methods inside of data() is not allowed in 2.x?

### ISSUE THREAD

**Issue by tzurbaev** [vuejs/vue#4302]
### Vue.js version
2.1.0

### Reproduction Link
http://jsfiddle.net/ds8o0kry/

### Steps to reproduce
Call any method inside of `data()` function

### What is Expected?
Method should be called (just like in 1.x)

### What is actually happening?
`Uncaught TypeError: %method% is not a function` is thrown

We are migrating from vue 1.0.28 to 2.x and seems that `data()` behaviour changed but there's no info in migration guide, vue-migration-helper also says nothing about this. Is this a bug or possibility of calling methods inside `data()` was removed?

**Comment by tzurbaev** [comment]
@mbj36 this bug was fixed in v2.1.4, so you need to update Vue if you're still on old version.

**Comment by ijunaid8989** [comment]
we still cannot call a method within a data?

**Comment by pauliuuso** [comment]
We can't call it too, on 2.5.21 version

**Comment by ijunaid8989** [comment]
Then why this issue is closed?

**Comment by jonasnordlund** [comment]
This does work. Pay attention to the posted jsfiddle. It opened with Javascript in the "no library (pure JS)" mode. As soon as I picked VueJS 2.2.1 from there (confirmed to work on 2.6.10 as well), it started giving the expected result.
