### ISSUE TITLE
Template compilation error in style attribute with url

### ISSUE THREAD

**Issue by Mottokrosh** [vuejs/vue#4346]
I ran into this issue yesterday. I'm working on a page that includes images with CSS shape-outside for flowing the text around them based on a shape image. To do this, I include the URL to the shape image in an inline style attribute.

During my work this stopped working after I upgraded Vue to the latest. The earliest reproducible version is 2.0.6. It's working on 2.0.5. When the HTML is compiled, the url from the style attribute string gets broken, and instead of the full URL you just end up with "http".

### Vue.js version
2.0.6+

### Reproduction Link
https://jsfiddle.net/mottokrosh/5Lppm3ce/7/

### Steps to reproduce
Go to the above JSBin. Ignore the CORS error about failing to load the shape image. 

### What is Expected?
Inspect the HTML of the `<figure>` in the dev console. The full `style="shape-outside: url(https://grove.sidhewoods.com/assets/verdant-reaches-players-guide/art/NPC_Sheriff_Lucas_Quint-shape.png); shape-margin: 1rem;"` should be seen, as in the specified HTML. 

### What is actually happening?
Instead, it's become `style="shape-outside: url("https"); shape-margin: 1rem;"`.

**Comment by defcc** [comment]
Thanks @Mottokrosh, I'm looking into it
