### ISSUE TITLE
[2.7.x] [typescript] Type inference breaks under specific circumstances

### ISSUE THREAD

**Issue by last-partizan** [vuejs/vue#12902]
### Version
2.7.14

### Reproduction link
[github.com](https://github.com/last-partizan/vue-examples/tree/ca959a619ee76daae9fea36c4b0370ed406d1628)

Or create this file in minimal vue-ts (v2) project

```ts
import {defineComponent} from "vue";

import App from "./App.vue";

export default defineComponent({
  // comment next line, and it works fine.
  components: {App},
  // or uncomment next line, and it works fine
  //props: {},
  data() {
    return {};
  },
  provide(): any {
    return {
      fetchData: this.fetchData,
    };
  },
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      throw new Error("Not implemented.");
    },
  },
});
```

### Steps to reproduce
Clone example repo, run `pnpm install`, run `pnpm vue-tsc`

### What is expected?
No errors.

### What is actually happening?
```
src/broken-method-type.ts:15:23 - error TS2339: Property 'fetchData' does not exist on type 'CreateComponentPublicInstance ...
```

---
It works if you remove `components: ...` line, or add empty `props: {}`.

(This is continuation of https://github.com/vuejs/vue/issues/12628 which is not fixed completely, or happened again, in my project it was working with vue-tsc<1.0, but happened again after update)

**Comment by rudy-xhd** [comment]
It works with vue-tsc@1.1.3.

**Comment by last-partizan** [comment]
Confirmed, closing issue.
