### ISSUE TITLE
Support using result of Vue.extend in mixins

### ISSUE THREAD

**Issue by strantr** [vuejs/vue#5652]
### Version
2.3.3

### Reproduction link
[http://jsfiddle.net/zna06rq4/1/](http://jsfiddle.net/zna06rq4/1/)

### Steps to reproduce
Run fiddle, error will be shown in console:

```
Error in callback for watcher "hello": "TypeError: this.cb.call is not a function"
```

### What is expected?
"child" should be logged to the console via the watch handler in Child.

### What is actually happening?
The watch is not being fired

---
In strats.watch (https://github.com/vuejs/vue/blob/086ae4469b0200e94b1ad0f70771e57c63ce18af/src/core/util/options.js#L175) the function unconditionally converts child to an array.
If this has already been converted to an array (via a previous merge operation) it will convert it to a nested array `[[child]]`.

The fix for this seems to be updating line 175 to have:
`Array.isArray(child) ? child : [child]`

**Comment by dodas** [comment]
I always do `[].concat(whatMightBeArrayOrMightBeNot)` in case I need array and it's not obvious if variable is array or not.

**Comment by posva** [comment]
As said in the PR, you should use plain objects instead of `Vue.extend` for mixins: http://jsfiddle.net/yjw4nafL/

You can achieve something similar with `extend` too: 
http://jsfiddle.net/sg0db7no/

**Comment by strantr** [comment]
@posva We are using TypeScript with `@Component` decorators. The implementation of this decorator uses Vue.extend(options) in order to create the components.
We are then needing to extend/mixin functionality from multiple components, causing this issue.

How can we avoid this problem when we do not have the ability to change the underlying component that we have - are you telling me that I cannot use Vue and TypeScript in this scenario when a simple change to the code would fix this?

**Comment by posva** [comment]
Ideally, the mixin should not be a component, otherwise, you can extend them with `Vue.extend` but you loose the ability to extend multiple things at the same time

**Comment by posva** [comment]
Why do you use the `@Component` decorator if you are exporting a Mixin?

**Comment by posva** [comment]
At the same time this should work: http://jsfiddle.net/q1f9f6ts/
So this may be a bug 🤔

**Comment by ktsn** [comment]
Actually, I implemented mixins for constructors in the past. The motivation was class style declaration is TypeScript friendly than objects.

**Comment by posva** [comment]
is it possible to have a different decorator to support the friendly declarations but not wrapping the object with `Vue.extend`?

**Comment by ktsn** [comment]
I think wrapping `Vue.extend` is needed since it simply uses `Ctor.options` on merging mixins. AFAIK, most of Vue component decorators are also using `Vue.extend`.

**Comment by strantr** [comment]
There may be some other factors going on here, I've created an example that uses `.extend` inside a vue-router and it works in Chrome (57.0.2987.133) and not Firefox (53.0.2).

http://jsfiddle.net/sn7p2goh/2/

Error in firefox:
```
TypeError: this.cb.call is not a function
Stack trace:
run@https://unpkg.com/vue@2.3.3/dist/vue.js:2864:11
flushSchedulerQueue@https://unpkg.com/vue@2.3.3/dist/vue.js:2619:5
queueNextTick/<@https://unpkg.com/vue@2.3.3/dist/vue.js:661:11
nextTickHandler@https://unpkg.com/vue@2.3.3/dist/vue.js:608:7
```

This was actually the issue that I was having and I traced it to the code that my PR is for, however I do not see what would cause the difference between browsers.

**Comment by strantr** [comment]
I can't work out why it would work in Chrome but not FF, is anyone able to take a look/any ideas?

**Comment by backbone87** [comment]
Just a side note: `Vue.extend({}).options` will give an error in typescript because `typeof Vue` doesnt have an option property

**Comment by ktsn** [comment]
Yes, because it's not declared in declaration files due to undocumented API.

**Comment by backbone87** [comment]
Is it considered public API though? It would definitely be helpful for tools/libs/plugins that need reflection over a component or instance to have access to a normalized options object. In the best case with its own `NormalizedOptions` type/interface.

**Comment by strantr** [comment]
It seems that the difference in behaviour in Firefox vs all other browsers is caused by vue-router being present on the page:

Sample 1 includes vue-router (external resources) but does not use it - this will error in Firefox
http://jsfiddle.net/sn7p2goh/6/

Sample 2 has vue-router removed - this works
http://jsfiddle.net/sn7p2goh/7/

**Comment by strantr** [comment]
@posva 
I've finally figured out the root cause for this issue.
Every object in Firefox already has a "watch" member ([Object.prototype.watch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch)). 

This means that when it reaches the watch merge strat parent.watch is already true and so it merges into a single array.

I am unsure if I can actually write a unit test for this as the issue is only present in Gecko (only browser with watch support).

**Comment by posva** [comment]
Hey, nice job and thanks a lot for looking into it. Well, you can simulate adding the `watch` property to the Object prototype (and remove it afterwards). Are you sure you opened a PR, I couldn't find it 🙂
