### ISSUE TITLE
Uncaught TypeError: Object.entries is not a function on OSX

### ISSUE THREAD

**Issue by maarteNNNN** [vuejs/vue#8955]
[link](https://beautysalonfiore.be)

I'm this problem on OSX. On Windows, Android and Linux I don't encounter this problem. I have tried to rebuild it. Google it, found alot of non Vue related issues. It doesn't work on an iPad aswell. However on an iPhone it does. What's most likely this problem?

This project is build with vue-cli 3.0.5.
