### ISSUE TITLE
[2.7.x] [typescript] Type augmentation does not work

### ISSUE THREAD

**Issue by last-partizan** [vuejs/vue#12642]
### Version
2.7.4

### Reproduction link
[github.com](https://github.com/last-partizan/vue-examples/tree/62e7062af495f515a24ade4b10a815126ad6d6b0)

### Steps to reproduce
look at the example repo, or, install `vue@2.7.4` and add type augmentation:

```ts
// env.d.ts
declare module "vue/types/vue" {
  interface Vue {
    $t: (s: string) => string
  }
}
```

```ts
// broken-augment.ts
import {defineComponent} from "vue";

export default defineComponent({
  methods: {
    getTranslatedText() {
      return this.$t("hello.vue");
    },
  },
});
```

### What is expected?
Expected no erros.

### What is actually happening?
```
> pnpm vue-tsc
src/broken-augment.ts:6:14 - error TS2571: Object is of type 'unknown'.

6       return this.$t("hello.vue");
               ~~~~~~~


Found 1 error in src/broken-augment.ts:6
```

**Comment by jhxxs** [comment]
vue 2.7.8 still has this problem

![image](https://user-images.githubusercontent.com/7448223/180731016-5f2271bb-9a37-492f-8d8b-8bc47c27d8a7.png)

**Comment by last-partizan** [comment]
That's strange.

In my production code this is indeed resolved, but in my minimal example: https://github.com/last-partizan/vue-examples/tree/692569fa503c0511cd10d771432222980b6afc49

There still a problem after updating to 2.7.8.

**Comment by jhxxs** [comment]
> vue 2.7.8 still has this problem
> 
> ![image](https://user-images.githubusercontent.com/7448223/180731016-5f2271bb-9a37-492f-8d8b-8bc47c27d8a7.png)

sorry, my bad, turns out i forget to add 

```ts
export {}
```

at last line

**Comment by axetroy** [comment]
vue 2.7.14 still has this problem

```typescript
import Vue from 'vue'

// not working
declare module 'vue/types/vue' {
    export interface Vue {
        test(): void
    }

    export interface VueConstructor {
        test(): void
    }
}

// Here is my solutoin
// works with defineComponent()
declare module 'vue/types/v3-component-options' {
    export interface MethodOptions {
        test(): void
    }
}

export {}
```
